### ISSUE TITLE
Emitting created files should be optional

### ISSUE THREAD

**Issue by pouyaemami** [olegstepura/typed-css-modules-loader#16]
The following line is causing issues as files are emitted to the output path of webpack when webpack is run. It would be great to have the option to turn this off.

```javascript
// Emit the created content as well
this.emitFile(content.outputFilePath, content.contents || [''], map);
```

Please let me know if you would like me to put up a PR

**Comment by olegstepura** [comment]
Sure PR is welcomed. If you wish to create a PR, please also update README on additional option available (with example). Currently loader has no it's own options.
