### ISSUE TITLE
Usage of reserved words as classnames will emit an error

### ISSUE THREAD

**Issue by AlexFrazer** [olegstepura/typed-css-modules-loader#18]
To reproduce:

- make a styles file like this:
```
.switch {
  display: flex;
}
```

It will emit a `styles.scss.d.ts` file, like so:
```
export const switch: number;
```

Of course, this will emit a syntax error because `switch` is a reserved word in javascript

**Comment by olegstepura** [comment]
A solution?

**Comment by olegstepura** [comment]
This relates to https://github.com/Quramy/typed-css-modules since this loader does not create the .d.ts itself.
