### ISSUE TITLE
Example working with any typescript loader?

### ISSUE THREAD

**Issue by mohsen1** [olegstepura/typed-css-modules-loader#3]
I'm working on this project that uses TypeScript and I was hoping that I can use typed-css-modules with it. 

I'm not sure entirely sure where this loader should be used. Currently I have my webpack config this way:

``` ts
import * as webpack from 'webpack';
import {join as joinPath} from 'path';
import {Configuration} from 'webpack';

const config: Configuration = {
    resolve: {
        extensions: ['', '.js', '.css', '.css.d.ts', '.ts', '.tsx'],
        root: __dirname,
        modulesDirectories: ['node_modules']
    },
    entry: {
        client: 'client'
    },
    output: {
        path: joinPath(__dirname, 'dist'),
        filename: '[name].js'
    },
    module: {
        loaders: [
            {
                test: /\.tsx?$/,
                loader: 'awesome-typescript-loader',
                exclude: 'node_modules'
            },
            {
                test: /\.css$/,
                exclude: /node_modules/,
                loaders: ['css-loader?modules']
            }
        ],
        preLoaders: [
            {
                test: /\.css$/,
                exclude: /node_modules/,
                loaders: ['typed-css-modules']
            }
        ]
    }
};

export default config;
```

But I get syntax errors as if the CSS code is being loaded by TypeScript. 

My project is open source. Please take a look at css-modules branch here: 
https://github.com/rah-foundation/website/tree/css-modules

**Comment by olegstepura** [comment]
Hi! I'm planning to add support for it in my test configuration for awesome-typescript-loader. Will notify you when ready

**Comment by olegstepura** [comment]
@mohsen1 There is logical error in https://github.com/rah-foundation/website/blob/75c4be4cacbfe94c6a1f850d30370e9135354152/webpack.config.ts

```
            {
                test: /\.css$/,
                exclude: /node_modules/,
                loader: 'ts-loader'
            }
```

You should load css with the loader that was designed to load css. `typed-css-loader` generates `.d.ts` files that are loaded by Typescript. It is not a final loader for css.

**Comment by mohsen1** [comment]
I've tried many different approaches with no luck. I would appreciate if you check out that project and fiddle with it a bit. I'm having the simplest setup possible and yet I can't make it work.

**Comment by mohsen1** [comment]
For anyone looking I figured it out. Here is a simple setup with HMR, Less and everything else:

https://github.com/rah-foundation/website/tree/247f54adc579f926ecc3b2ff548c86ac23e9f4f9

Although HMR is not working for Less files at that SHA

**Comment by olegstepura** [comment]
@mohsen1 so we can close this?

**Comment by mohsen1** [comment]
Sure
