### ISSUE TITLE
Invokes HMR reload whole application starting from entry

### ISSUE THREAD

**Issue by genaby** [olegstepura/typed-css-modules-loader#6]
HMR posts into browser patch with every single module, as result application is reloaded by any change in CSS.

**Comment by olegstepura** [comment]
Hi! I need more details. HMR is expected to send patches when module is changed, it's a desired behaviour.

**Comment by genaby** [comment]
HMR works fine if it is removed from pre-loaders, and patches only updated files and its dependencies. 
Details: 
`styles!css?modules&localIdentName=[name]_[local]_[hash:base64:5]!postcss!resolve-url!sass?sourceMap`
with numerous  SASS imports
e.g.:

```
@import "../../../../scss/classes/tables";
@import "../../../../scss/consts/bg-images";

$proportion: 37%;

th {
  &.status { width: 12%; }
  &.reporting { width: 8%; }
  &.modified { width: 8%; }
...
```

and there are few TS files which import multiply style modules.

So webpack has a crazy graph of dependencies.

I'll try to reproduce this issue again later... please let me know what details do you need.

**Comment by olegstepura** [comment]
Hi! Seems like a [known issue](https://github.com/Quramy/typed-css-modules/issues/2#issuecomment-229316743). I also experienced the issue that newly created files were not processed. 
Please take a look here https://github.com/Quramy/typed-css-modules/issues/2
Currently we have no solution to this.
